xcodeproj 'ToDoTaskList.xcodeproj'

platform :ios, '5.0'

pod 'Reachability',  '~> 3.0.0'
pod 'AeroGear', :git => 'https://github.com/aerogear/aerogear-ios.git'
pod 'ARGenericTableViewController', :git => 'https://github.com/corinnekrych/ARGenericTableViewController.git'